---
pygments: true
permalink: /:year/:month/:title
base: http://docs.sensuapp.org
current_version: 0.9
server_port: 80
title: Sensu Docs
author: Sean Porter
email: sean.porter@gmail.com

exclude: [ config.ru, sass, config.rb, Rakefile, TODO, README.markdown, tasks, config, Capfile]

markdown: maruku
